modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Natank25/SCP-Build-your-own/issues"
license = "All Rights Reserved"

[[mods]]
modId = "scp_byo"
version = "${version}"
displayName = "SCP: Build Your Own"
authors = "Natank25"
description = '''
A nice mod that allows you to build the SCP Foundation in minecraft, with all the functionalities that are expected
'''
logoFile = "mod_icon.png"

[[dependencies.scp_byo]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scp_byo]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scp_byo]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.scp_byo]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "scp_byo.mixins.json"
